apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: superapp-controller-knp
  labels:
    strimzi.io/cluster: superapp-cluster
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 1Gi
    class: standard
    deleteClaim: false
