apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
  - ../../../base/kafka

nameSuffix: -dev

# Example prod override (optional)
# patches:
#   - target:
#       kind: KafkaNodePool
#     patch: |-
#       - op: replace
#         path: /spec/replicas
#         value: 1
